services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ## Registries ##
    IDCI\Bundle\TaskBundle\ExtractRule\ExtractRuleRegistry: ~

    IDCI\Bundle\TaskBundle\Action\ActionRegistry: ~

    ## Factory ##
    IDCI\Bundle\TaskBundle\Factory\TaskFactory:
        arguments:
            $applicationName: '%application_name%'
            $taskConfigurationClass: '%idci_task.task_configuration_class%'
            $workflowHandler: '@IDCI\Bundle\TaskBundle\Handler\WorkflowHandler'

    ## Actions ##
    IDCI\Bundle\TaskBundle\Action\AbstractAction:
        autowire: false
        autoconfigure: false
        abstract: true
        calls:
            - [setLogger, ['@monolog.logger.idci_task.action']]
            - [setTaskLogProcessor, ['@IDCI\Bundle\TaskBundle\Monolog\Processor\TaskLogProcessor']]

    ## Subscriber ##
    IDCI\Bundle\TaskBundle\Event\Subscriber\ExtractedDataSubscriber:
        arguments:
            $taskProducer: '@old_sound_rabbit_mq.task_producer'
            $applicationName: '%application_name%'
        tags:
            - { name: kernel.event_subscriber }

    IDCI\Bundle\TaskBundle\Event\Subscriber\ProcessEventSubscriber:
        arguments:
            $processor: '@IDCI\Bundle\TaskBundle\Processor\RabbitMqProcessor'
        tags:
            - { name: kernel.event_subscriber }

    IDCI\Bundle\TaskBundle\Event\Subscriber\TaskEventSubscriber:
        arguments:
            $actionProducer: '@old_sound_rabbit_mq.action_producer'
            $documentManager: '@doctrine_mongodb.odm.document_manager'
        tags:
            - { name: kernel.event_subscriber }

    ## RabbitMQ consumers
    IDCI\Bundle\TaskBundle\RabbitMq\Consumer\ActionConsumer:
        arguments:
            $documentManager: '@doctrine_mongodb.odm.document_manager'
            $actionHandler: '@IDCI\Bundle\TaskBundle\Handler\ActionHandler'

    IDCI\Bundle\TaskBundle\RabbitMq\Consumer\ExtractRuleConsumer:
        arguments:
            $extractRuleRegistry: '@IDCI\Bundle\TaskBundle\ExtractRule\ExtractRuleRegistry'
            $extractRuleHandler: '@IDCI\Bundle\TaskBundle\Handler\ExtractRuleHandler'
            $taskConfigurationClass: '%idci_task.task_configuration_class%'

    IDCI\Bundle\TaskBundle\RabbitMq\Consumer\TaskConsumer:
        arguments:
            $taskHandler: '@IDCI\Bundle\TaskBundle\Handler\TaskHandler'

    ## Processor
    IDCI\Bundle\TaskBundle\Processor\RabbitMqProcessor:
        arguments:
            $extractRuleProducer: '@old_sound_rabbit_mq.extract_rule_producer'
            $taskProducer: '@old_sound_rabbit_mq.task_producer'
            $actionProducer: '@old_sound_rabbit_mq.action_producer'
            $documentManager: '@doctrine_mongodb.odm.document_manager'
            $applicationName: '%application_name%'
            $taskConfigurationClass: '%idci_task.task_configuration_class%'

    ## Handler ##
    IDCI\Bundle\TaskBundle\Handler\ActionHandler:
        arguments:
            $registry: '@IDCI\Bundle\TaskBundle\Action\ActionRegistry'
            $dispatcher: '@event_dispatcher'
            $merger: '@twig'
            $actionProducer: '@old_sound_rabbit_mq.action_producer'
            $workflowHandler: '@IDCI\Bundle\TaskBundle\Handler\WorkflowHandler'
            $logger: '@monolog.logger.idci_task.action'
            $taskLogProcessor: '@IDCI\Bundle\TaskBundle\Monolog\Processor\TaskLogProcessor'

    IDCI\Bundle\TaskBundle\Handler\ExtractRuleHandler:
        arguments:
            $registry: '@IDCI\Bundle\TaskBundle\ExtractRule\ExtractRuleRegistry'
            $dispatcher: '@event_dispatcher'
            $extractRuleProducer: '@old_sound_rabbit_mq.extract_rule_producer'
            $applicationName: '%application_name%'

    IDCI\Bundle\TaskBundle\Handler\TaskHandler:
        arguments:
            $taskFactory: '@IDCI\Bundle\TaskBundle\Factory\TaskFactory'
            $documentManager: '@doctrine_mongodb.odm.document_manager'
            $dispatcher: '@event_dispatcher'

    IDCI\Bundle\TaskBundle\Handler\WorkflowHandler:
        arguments:
            $merger: '@twig'
            $documentManager: '@doctrine_mongodb.odm.document_manager'
            $registry: '@IDCI\Bundle\TaskBundle\Action\ActionRegistry'


    ## Configuration rule ##
    IDCI\Bundle\TaskBundle\ExtractRule\ExtractRuleConfigurationRule:
        arguments:
            $extractRuleRegistry: '@IDCI\Bundle\TaskBundle\ExtractRule\ExtractRuleRegistry'
        tags:
            - {name: 'idci_configuration_validator.configuration.rule', alias: 'extract_rule'}

    IDCI\Bundle\TaskBundle\Action\ActionConfigurationRule:
        arguments:
            $actionRegistry: '@IDCI\Bundle\TaskBundle\Action\ActionRegistry'
        tags:
            - {name: 'idci_configuration_validator.configuration.rule', alias: 'action'}

    ## Configurations ##
    IDCI\Bundle\TaskBundle\ExtractRule\ExtractRule:
        arguments: [null]
        abstract: true

    IDCI\Bundle\TaskBundle\Action\Action:
        arguments: [null]
        abstract: true

    ## Monolog ##
    IDCI\Bundle\TaskBundle\Monolog\Processor\TaskLogProcessor:
        tags:
            - { name: monolog.processor, method: processRecord, handler: mongo }

    ## FormType ##
    IDCI\Bundle\TaskBundle\Form\Type\ExtractRuleEditorType:
       tags:
           - { name: form.type, alias: extract_rule_editor }
           - { name: idci_asset_loader.asset_provider, alias: extract_rule_editor }

    IDCI\Bundle\TaskBundle\Form\Type\WorkflowEditorType:
        tags:
            - { name: form.type, alias: workflow_editor }
            - { name: idci_asset_loader.asset_provider, alias: workflow_editor }
